version: '3'
services:
  app:
    build:
      context: .
      args:
        UID: ${UID-1000}
    user: ${UID-1000}
    command: npm run start
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - .:/app
