name: deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-20.04
    env:
      USER_HOST: ubuntu@18.157.76.28
      HOST_KEY: 18.157.76.28 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBAqq2+h1IlKJCIJUtJfSfFJTqBodnEgxY+68slANQCWtFIVLsH3nesiZmybgrDeT4NM/T+o13ogHNY50IC3mQhY=
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up ssh
        run: |
          set -x
          mkdir ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 0600 ~/.ssh/id_rsa
          echo "$HOST_KEY" >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy
        run: |
          set -x
          BRANCH=${GITHUB_REF#refs/heads/}
          cat .github/deploy.sh | ssh -Ti ~/.ssh/id_rsa "$USER_HOST" sh -s "$BRANCH"
